[linux]
10.0.1.4 ansible_user=azureuser
10.0.1.5 ansible_user=azureuser

[linux:vars]
ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa
ansible_ssh_common_args='-o ProxyJump=azureuser@BASTION_PUBLIC_IP'
[windows]
10.0.1.6 ansible_user=azureuser 