---
- name: Configure Windows VM
  hosts: windows

  tasks:

  - name: Install IIS
    win_feature:
      name: Web-Server
      state: present
      include_management_tools: yes
  - name: Copy custom IIS page
    win_copy:
      src: ../files/iis.html
      dest: C:\inetpub\wwwroot\iisstart.htm