---
- name: Configure web server
  hosts: linux
  become: yes

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Ensure nginx running
      service:
        name: nginx
        state: started
        enabled: yes