---
- name: Configure Linux VM
  hosts: linux
  become: yes

  tasks:

  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Copy custom web page
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: yes