---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Ensure NGINX started
  service:
    name: nginx
    state: started
    enabled: yes